CREATE DATABASE ngac IF NOT EXISTS;
CREATE ROLE ngac_access IF NOT EXISTS;
GRANT ACCESS ON DATABASE ngac TO ngac_access;
GRANT MATCH {*} ON GRAPH * TO ngac_access;
GRANT WRITE ON GRAPH * TO ngac_access;
GRANT NAME MANAGEMENT ON DATABASE ngac TO ngac_access;
CREATE USER www IF NOT EXISTS SET PASSWORD 'password' CHANGE NOT REQUIRED SET STATUS ACTIVE;
GRANT ROLE ngac_access TO www;